---

- name: Create install directory
  file: path=/opt/codeception owner=root group=root state=directory
  sudo: yes

- name: Check for existence of git repo
  stat: path=/opt/codeception/.git
  register: cc_git

- name: Empty directory if not using git version of codeception yet
  shell: rm -rf /opt/codeception/*
  sudo: yes
  when: cc_git.stat.isdir is not defined or cc_git.stat.isdir == false

- name: Download codeception
  git:
    repo=https://github.com/Codeception/Codeception.git
    dest=/opt/codeception
    version=9c7f23eff3e607225e9f43277c6d9cdb03d30b84
  sudo: yes
  register: cc_checkout

- name: Check for codeception composer lock
  stat: path=/opt/codeception/composer.lock
  register: cc_lock

- name: Install codeception dependencies
  shell: composer install --prefer-dist --working-dir=/opt/codeception
  sudo: yes
  when: (not cc_lock.stat.exists) or cc_checkout.changed

- name: Create symlink
  file: src=/opt/codeception/codecept dest=/usr/local/bin/codecept state=link
  sudo: yes
