---

- name: Create install directory
  file: path=/opt/codeception owner=root group=root state=directory
  sudo: yes

- name: Download codeception
  git:
    repo=https://github.com/Codeception/Codeception.git
    dest=/opt/codeception
    version=5b2448d48ce56f744077a83195fc92c73cc7ebeb
  sudo: yes

- name: Install codeception dependencies
  # Update seems to be necessary for some reason
  shell: composer update --prefer-dist --working-dir=/opt/codeception

- name: Create symlink
  file: src=/opt/codeception/codecept dest=/usr/local/bin/codecept state=link
  sudo: yes
